[package]
name = "pallet-evm-living-assets-ownership"
version = "2.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>", "Drew Stone <drew@commonwealth.im>"]
license = "Apache-2.0"
description = "Living assets ownership precompile"
repository = "https://github.com/freeverseio/pallet-livingassets-ownership"
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true, features = [
	"derive",
] }
scale-info = { workspace = true, features = [
	"derive",
] }

# Frontier
fp-evm = { workspace = true }
pallet-evm = { workspace = true }

# Substrate
frame-support = { workspace = true }
sp-arithmetic = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Local pallet
pallet-living-assets-ownership = { workspace = true }

# Utils
precompile-utils = { workspace = true }
precompile-utils-macro = { workspace = true }

num_enum = { workspace = true }

[dev-dependencies]
pallet-evm-test-vector-support = { workspace = true }
evm = { workspace = true }
hex = { version = "0.4.3" }

[features]
default = ["std"]
std = [
	# Frontier
	"fp-evm/std",
	"pallet-evm/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"pallet-living-assets-ownership/std",
	"num_enum/std",
	"frame-support/std",
	"sp-arithmetic/std",
	"precompile-utils/std",
	"parity-scale-codec/std",
	"scale-info/std",
]
