[package]
name = "laos-precompile-utils-macro"
authors = ["StakeTechnologies", "PureStake"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/tests.rs"

[dependencies]
num_enum = { workspace = true }
proc-macro2 =  { workspace = true }
quote = { workspace = true }
sha3 = { workspace = true }
syn = { workspace = true, features = ["extra-traits", "fold", "full", "visit"] }
